apiVersion: v1
kind: Service
metadata:
  name: {{ include "aixcoder-statistics.fullname" . }}
  namespace: {{ include "global.namespace" . | quote }}
  labels:
    {{- include "aixcoder-statistics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: ClientIP    
  selector:
    {{- include "aixcoder-statistics.selectorLabels" . | nindent 4 }}
